services:
  backend:
    build: ./backend 
    image: dgelom/todo-backend-image:latest 
    env_file: 
      - .env-docker
    ports:
      - 3000:3000 

  frontend:
    build: ./frontend 
    image: dgelom/todo-frontend-image:latest
    ports:
      - 3001:3000 
    depends_on: 
      - backend