services:
  backend:
    build: ./backend 
    image: todo-backend-image:latest 
    ports:
      - 3000:3000 

  frontend:
    build: ./frontend 
    image: todo-frontend-image:latest
    ports:
      - 3001:3000 
    depends_on: 
      - backend