version: '3'
services:
  backend:
    build: ./backend 
    image: tofo-backend-image:latest 
    env_file: 
      - .env 
    ports:
      - 3000:3000 

  frontend:
    build: ./frontend 
    image: frontend-image:latest
    ports:
      - 3001:3000 
    depends_on: 
      - backend