name: Docker Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t todo-app:latest .
      env:
        DB_URI: ${{ secrets.DB_URI }}

    - name: Test Docker image
      run: |
        docker run -d --name todo-app-container todo-app:latest
        docker ps
        docker logs todo-app-container

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag todo-app:latest your-dockerhub-username/todo-app:latest
        docker push your-dockerhub-username/todo-app:latest