name: Docker Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend: # Nouveau job pour le backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Backend Docker image
      working-directory: backend 
      run: docker build -t todo-backend-image:latest .
      env:
        DB_URI: ${{ secrets.DB_URI }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag todo-backend-image:latest dgelom/todo-backend-image:latest
        docker push dgelom/todo-backend-image:latest

  build-frontend: # Nouveau job pour le frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Frontend Docker image
      working-directory: frontend # Assurez-vous que c'est le bon répertoire
      run: docker build -t todo-frontend-image:latest .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag todo-frontend-image:latest dgelom/todo-frontend-image:latest
        docker push dgelom/todo-frontend-image:latest